### ISSUE TITLE
"Bitwarden Vault is locked"

### ISSUE THREAD

**Issue by WolfHeroEX** [RedMageKnight/Flow.Launcher.Plugin.BitwardenSearch#4] opened 2024-08-02 00:43 UTC
To the best of my knowledge, I've installed the CLI correctly. I've logged in via Terminal, and trying to log in further mentions I'm already logged in. The path seems set up correctly.

If trying to unlock via Terminal, it says it's successful. Subsequent attempts give me the password prompt again followed by another successful unlock.

If I try to unlock it via Flow Launcher, it closes immediately after pressing Enter. Trying to input a bw command again repeats that the vault is locked.

Any ideas as to what's going on?

**Comment by WolfHeroEX** [comment] 2024-08-02 01:22
[BitwardenFlow_20240801.log](https://github.com/user-attachments/files/16463958/BitwardenFlow_20240801.log)
It's mentioning that the master password is invalid, though I'm sure it's correct. I do have two-step authentication set up, is that causing issues with the login?

**Comment by RedMageKnight** [comment] 2024-08-02 01:29
Okay, it shouldn't be if you log in with your Bitwarden credentials via the terminal first by doing bw login, and then go through the whole login process (it'll ask for your email, it'll ask for your master password, and then it should prompt you for MFA however you have it configured). Once you do this, you should be able to close your terminal, make sure you have your client id and client secret provided in the settings, restart Flow Launcher completely (full close from notification tray and then reopen) and then unlock Bitwarden through the plugin through your master password.

I'm planning on fixing it now with the latest CLI version so you won't have to do the regular terminal login process first going forward, but that's a piece I have to work on now that it's been fixed with the new version. 

In the meantime, that's the process that should work, so if you can go through that process again and let me know how it works for you, I'd appreciate it!

**Comment by WolfHeroEX** [comment] 2024-08-02 01:43
No dice. Logged in via terminal, closed it, restarted flow launcher, attempted an unlock. Asked for an unlock again.

To be clear, it would be formatted as bw /unlock passwordtext, correct? I assumed the ` and <> wasn't necessary.

**Comment by RedMageKnight** [comment] 2024-08-02 01:53
Yes, that's correct. After you logged in from the terminal, did it give you a session key as the output? If it did, did you make sure to have your client id and client secret entered in settings and then restart Flow Launcher completely and then try and unlock? When you try and unlock, do you have a sessionKey value defined in the Flow Launcher plugin settings file (typically %appdata%\FlowLauncher\Settings\Plugins\Flow.Launcher.Plugin.BitwardenSearch\BitwardenFlowSettings.json)?

I'm sorry it's not working for you, I'm wondering if it's a result of the change in the CLI version you're using (which is the newest 2024.7.2 - I had tested this method with the previous version 2024.7.1). I'm in the middle of trying to update the plugin now to use the --apikey parameter proper with this update which I've confirmed works from the CLI, but it's taking me a bit to work through it.

**Comment by WolfHeroEX** [comment] 2024-08-02 01:58
The terminal did give me a session key. Client ID and Secret are correctly entered, and it's been restarted. No session key in the json file after the unlock attempt, I tried adding the key from the terminal output as a last ditch effort and that got replaced with nothing on reload.

**Comment by WolfHeroEX** [comment] 2024-08-02 02:11
I'm not actually sure how to go about finding the older cli for installation, could you provide me with it?

**Comment by RedMageKnight** [comment] 2024-08-02 02:15
This should be it: https://github.com/bitwarden/clients/releases/tag/cli-v2024.7.1

**Comment by WolfHeroEX** [comment] 2024-08-02 02:22
Still no dice, sadly. I placed the older bw.exe in, relauched everything, re-logged in on the terminal, closed it out and restarted flow. I tried again to unlock, it closed and asked again after I typed in bw.

**Comment by RedMageKnight** [comment] 2024-08-02 02:24
Ah okay, thanks for letting me know; I'm continuing to work through this new version and I'll let you know when it's released and hopefully that'll work better for you :)

**Comment by RedMageKnight** [comment] 2024-08-05 00:45
Hi @WolfHeroEX!

Just wanted to let you know that I'm making some headway on my version 1.3.0 which should hopefully resolve this issue as well as a number of other issues and quality of life fixes I wanted to implement. I'll let you know as soon as I have it available :)

**Comment by flooxo** [comment] 2024-08-05 20:25
Same for me.
But thanks for the great plugin :)

**Comment by flooxo** [comment] 2024-08-05 20:45
After I manually inserted the session key from the command line into the `settings.json` file, it worked for me and created a custom key on restart+unlock.
Maybe there is a problem when the session key is empty for the first time? But this is just a wild guess

The only strange thing is that if you enter `bw` again after the `/unlock`, the query is simply deleted and sometimes the prompt "CLI not installed" appears. But if you just enter the keyword again, everything works as expected

Unfortunately, I don't know if any of that helps :/

**Comment by RedMageKnight** [comment] 2024-08-05 22:26
It does, thank you for your input! I started doing more comprehensive testing and experienced the same thing, although I've done quite a bit of refactoring and wasn't sure if it was 100% due to the existing logic or my changes at first until I added some more intentional methods to isolate the way the CLI is now reading the credentials.

I'm hoping to have 1.3.0 out really soon, but my work has been kicking my butt the past week and it's been difficult to devote a ton of time to it recently.

**Comment by abbasou** [comment] 2024-08-06 20:44
Just dropping in to add my +1 to this issue and to this plugin in general. Really looking forward to a functional FL plugin. Just to double-check, this plugin should work with a self-hosted BW server as long as that is configured correctly in the BW CLI, yes?

**Comment by flooxo** [comment] 2024-08-06 20:58
Yes, it works with a self-hosted BW server, as Vaultwarden (self-hosted BW) is designed to work with all upstream Bitwarden clients.

**Comment by RedMageKnight** [comment] 2024-08-11 22:08
Hi all!

I've released version 1.3.0 and this should improve a lot of the issues people were having in the initial setup process with some more guidance and automation from the plugin settings itself. If you wouldn't mind giving it a shot and letting me know, it'd be much appreciated!

Oh, and in order to use this plugin properly going forward, you'll need to update to the latest version of the Bitwarden CLI - 2024.7.2 finally fixed the login mechanism using the API and I've coded the login process explicitly around this as it should have been in the first place.

**Comment by abbasou** [comment] 2024-08-12 17:06
So I installed this manually (not updated on FL plugin store yet?) and fiddled around with it. It appears you have to unlock bw CLI in a shell first, and then the plugin will unlock. Is this expected behavior?

**Comment by RedMageKnight** [comment] 2024-08-12 19:23
So you updated to version 1.3.1 and you're using the 2024.7.2 version of the CLI correct? Both of these are important. You should not need to unlock from the shell first.

**Comment by abbasou** [comment] 2024-08-12 21:02
That is correct. I just tested as follows:
1. Verify in shell (cmd) that bw was locked.
2. BW FL was previously unlocked. Lock it.
3. Attempt to unlock BW FL. _Failed._
4. Unlock BW in shell.
5. Attempt to unlock in BW FL. _Success._

Using latest plugin v. 1.3.1; using latest bw.exe v. 2024.7.2

**Comment by RedMageKnight** [comment] 2024-08-13 00:51
After you lock your vault from the console and you lock your vault from the plugin, can you try closing out of Flow Launcher and then navigating to %appdata%/Bitwarden CLI and deleting the data.json file in there and trying to go through the process again of logging in and unlocking through Flow Launcher? I have seen issues previously, even on a brand new setup, that the CLI messes up and that data file needs to be cleared out. If that doesn't work, can you enable all the logs and send me your log from the Bitwarden plugin folder after you've tried to unlock your vault from Flow Launcher?

I did an end-to-end brand new setup today on a separate computer that never had Flow Launcher installed or used the CLI before and I downloaded the new version of the plugin from the store and it pretty much worked as expected.

**Comment by abbasou** [comment] 2024-08-13 18:35
Ok so here we go. Tried various things, but ultimately here's the cleanest version of what I have tried so far.
1. Close FL, _logout_ of BW CLI. Delete data.json from `C:\Users\[user]\AppData\Roaming\Bitwarden CLI`
2. Delete everything inside the plugin folder `C:\Users\[user]\AppData\Roaming\FlowLauncher\Plugins\Bitwarden-1.3.1` and copy back from freshly downloaded .zip
3. In console, `bw config server [self-hosted server]`
4. Run FL. Open BW plugin settings, enter Client ID and Client Secret from web vault. (Also set autolock timer)
5. Attempt to _unlock_ plugin; _failed._
6. Unlock on console, reattempt to unlock plugin; _failed._
7. Close and restart FL, attempt again; _failed._

I apparently have regressed somehow. lol. 

>2024-08-13 12:22:16 [Warning] - Client ID is not set
2024-08-13 12:22:18 [Error] - [REDACTED SENSITIVE INFORMATION]
2024-08-13 12:22:18 [Error] - Failed to log in
2024-08-13 12:22:39 [Warning] - Client ID is not set
2024-08-13 12:22:39 [Warning] - Client ID is not set
2024-08-13 12:22:39 [Warning] - Client ID is not set
2024-08-13 12:22:39 [Warning] - Client ID is not set
2024-08-13 12:22:39 [Warning] - Client ID is not set
2024-08-13 12:22:39 [Warning] - Client ID is not set
2024-08-13 12:22:39 [Warning] - Client ID is not set
2024-08-13 12:22:39 [Warning] - Client ID is not set
2024-08-13 12:22:48 [Warning] - Client ID is not set
2024-08-13 12:22:48 [Warning] - Client ID is not set
2024-08-13 12:23:09 [Error] - Error checking login status: You are not logged in.
2024-08-13 12:23:09 [Warning] - [REDACTED SENSITIVE INFORMATION]
2024-08-13 12:23:21 [Info] - Verifying and applying settings
2024-08-13 12:23:22 [Debug] - Auto-lock timer disabled
2024-08-13 12:23:22 [Info] - Verifying and applying settings
2024-08-13 12:23:22 [Debug] - Auto-lock timer disabled
2024-08-13 12:23:22 [Info] - Verifying and applying settings
2024-08-13 12:23:22 [Debug] - [REDACTED SENSITIVE INFORMATION]
2024-08-13 12:23:22 [Debug] - [REDACTED SENSITIVE INFORMATION]
2024-08-13 12:23:22 [Info] - [REDACTED SENSITIVE INFORMATION]
2024-08-13 12:23:22 [Info] - Settings verified and applied successfully
2024-08-13 12:23:23 [Debug] - [REDACTED SENSITIVE INFORMATION]
2024-08-13 12:23:23 [Debug] - [REDACTED SENSITIVE INFORMATION]
2024-08-13 12:23:23 [Info] - [REDACTED SENSITIVE INFORMATION]
2024-08-13 12:23:23 [Info] - Settings verified and applied successfully
2024-08-13 12:23:23 [Debug] - [REDACTED SENSITIVE INFORMATION]
2024-08-13 12:23:23 [Debug] - [REDACTED SENSITIVE INFORMATION]
2024-08-13 12:23:23 [Info] - [REDACTED SENSITIVE INFORMATION]
2024-08-13 12:23:23 [Info] - Settings verified and applied successfully
2024-08-13 12:23:41 [Debug] - [REDACTED SENSITIVE INFORMATION]
2024-08-13 12:23:42 [Info] - Bitwarden CLI found. Version: 2024.7.2
2024-08-13 12:23:42 [Debug] - Executing HandleBitwardenSearch
2024-08-13 12:23:42 [Debug] - Auto-lock timer reset
2024-08-13 12:23:42 [Debug] - HandleBitwardenSearch called with query: [EMPTY QUERY]
2024-08-13 12:23:42 [Warning] - Vault is considered locked
2024-08-13 12:23:42 [Debug] - [REDACTED SENSITIVE INFORMATION]
2024-08-13 12:23:43 [Debug] - [REDACTED SENSITIVE INFORMATION]
2024-08-13 12:23:43 [Info] - Bitwarden CLI found. Version: 2024.7.2
2024-08-13 12:23:43 [Debug] - Executing HandleBitwardenSearch
2024-08-13 12:23:43 [Debug] - Auto-lock timer reset
2024-08-13 12:23:43 [Debug] - HandleBitwardenSearch called with query: [EMPTY QUERY]
2024-08-13 12:23:43 [Warning] - Vault is considered locked
2024-08-13 12:23:43 [Info] - Bitwarden CLI found. Version: 2024.7.2
2024-08-13 12:23:43 [Debug] - Executing HandleBitwardenSearch
2024-08-13 12:23:43 [Debug] - Auto-lock timer reset
2024-08-13 12:23:43 [Debug] - HandleBitwardenSearch called with query: /
2024-08-13 12:23:43 [Warning] - Vault is considered locked
2024-08-13 12:23:43 [Debug] - [REDACTED SENSITIVE INFORMATION]
2024-08-13 12:23:44 [Debug] - [REDACTED SENSITIVE INFORMATION]
2024-08-13 12:23:44 [Info] - Bitwarden CLI found. Version: 2024.7.2
2024-08-13 12:23:44 [Debug] - Executing HandleBitwardenSearch
2024-08-13 12:23:44 [Debug] - Auto-lock timer reset
2024-08-13 12:23:44 [Debug] - HandleBitwardenSearch called with query: /u
2024-08-13 12:23:44 [Warning] - Vault is considered locked
2024-08-13 12:23:44 [Debug] - [REDACTED SENSITIVE INFORMATION]
2024-08-13 12:23:44 [Debug] - [REDACTED SENSITIVE INFORMATION]
2024-08-13 12:23:44 [Info] - Bitwarden CLI found. Version: 2024.7.2
2024-08-13 12:23:44 [Debug] - Executing HandleBitwardenSearch
2024-08-13 12:23:44 [Debug] - Auto-lock timer reset
2024-08-13 12:23:44 [Debug] - HandleBitwardenSearch called with query: /un
2024-08-13 12:23:44 [Warning] - Vault is considered locked
2024-08-13 12:23:44 [Debug] - [REDACTED SENSITIVE INFORMATION]
2024-08-13 12:23:45 [Debug] - [REDACTED SENSITIVE INFORMATION]
2024-08-13 12:23:45 [Info] - Bitwarden CLI found. Version: 2024.7.2
2024-08-13 12:23:45 [Debug] - Executing HandleBitwardenSearch
2024-08-13 12:23:45 [Debug] - Auto-lock timer reset
2024-08-13 12:23:45 [Debug] - HandleBitwardenSearch called with query: /unl
2024-08-13 12:23:45 [Warning] - Vault is considered locked
2024-08-13 12:23:45 [Info] - Bitwarden CLI found. Version: 2024.7.2
2024-08-13 12:23:45 [Debug] - Executing HandleBitwardenSearch
2024-08-13 12:23:45 [Debug] - Auto-lock timer reset
2024-08-13 12:23:45 [Debug] - HandleBitwardenSearch called with query: /unlo
2024-08-13 12:23:45 [Warning] - Vault is considered locked
2024-08-13 12:23:45 [Info] - Bitwarden CLI found. Version: 2024.7.2
2024-08-13 12:23:45 [Debug] - Executing HandleBitwardenSearch
2024-08-13 12:23:45 [Debug] - Auto-lock timer reset
2024-08-13 12:23:45 [Debug] - HandleBitwardenSearch called with query: /unlock
2024-08-13 12:23:45 [Info] - Bitwarden CLI found. Version: 2024.7.2
2024-08-13 12:23:45 [Debug] - Executing HandleBitwardenSearch
2024-08-13 12:23:45 [Debug] - Auto-lock timer reset
2024-08-13 12:23:45 [Debug] - HandleBitwardenSearch called with query: /unloc
2024-08-13 12:23:45 [Warning] - Vault is considered locked
2024-08-13 12:23:46 [Debug] - [REDACTED SENSITIVE INFORMATION]
2024-08-13 12:23:47 [Debug] - [REDACTED SENSITIVE INFORMATION]
2024-08-13 12:23:47 [Info] - Bitwarden CLI found. Version: 2024.7.2
2024-08-13 12:23:47 [Debug] - Executing HandleBitwardenSearch
2024-08-13 12:23:47 [Debug] - Auto-lock timer reset
2024-08-13 12:23:47 [Debug] - HandleBitwardenSearch called with query: /unlock
2024-08-13 12:23:47 [Info] - Bitwarden CLI found. Version: 2024.7.2
2024-08-13 12:23:47 [Debug] - Executing HandleBitwardenSearch
2024-08-13 12:23:47 [Debug] - Auto-lock timer reset
2024-08-13 12:23:47 [Debug] - HandleBitwardenSearch called with query: /unlock [REDACTED]
2024-08-13 12:23:48 [Debug] - [REDACTED SENSITIVE INFORMATION]
2024-08-13 12:23:48 [Debug] - [REDACTED SENSITIVE INFORMATION]
2024-08-13 12:23:48 [Debug] - [REDACTED SENSITIVE INFORMATION]
2024-08-13 12:23:48 [Info] - Bitwarden CLI found. Version: 2024.7.2
2024-08-13 12:23:48 [Debug] - Executing HandleBitwardenSearch
2024-08-13 12:23:48 [Debug] - Auto-lock timer reset
2024-08-13 12:23:48 [Debug] - HandleBitwardenSearch called with query: /unlock [REDACTED]
2024-08-13 12:23:48 [Debug] - [REDACTED SENSITIVE INFORMATION]
2024-08-13 12:23:49 [Debug] - [REDACTED SENSITIVE INFORMATION]
2024-08-13 12:23:49 [Info] - Bitwarden CLI found. Version: 2024.7.2
2024-08-13 12:23:49 [Debug] - Executing HandleBitwardenSearch
2024-08-13 12:23:49 [Debug] - Auto-lock timer reset
2024-08-13 12:23:49 [Debug] - HandleBitwardenSearch called with query: /unlock [REDACTED]
2024-08-13 12:23:49 [Info] - Bitwarden CLI found. Version: 2024.7.2
2024-08-13 12:23:49 [Debug] - Executing HandleBitwardenSearch
2024-08-13 12:23:49 [Debug] - Auto-lock timer reset
2024-08-13 12:23:49 [Debug] - HandleBitwardenSearch called with query: /unlock [REDACTED]
2024-08-13 12:23:49 [Debug] - [REDACTED SENSITIVE INFORMATION]
2024-08-13 12:23:49 [Info] - Bitwarden CLI found. Version: 2024.7.2
2024-08-13 12:23:49 [Debug] - Executing HandleBitwardenSearch
2024-08-13 12:23:49 [Debug] - Auto-lock timer reset
2024-08-13 12:23:49 [Debug] - HandleBitwardenSearch called with query: /unlock [REDACTED]
2024-08-13 12:23:49 [Debug] - [REDACTED SENSITIVE INFORMATION]
2024-08-13 12:23:49 [Info] - Bitwarden CLI found. Version: 2024.7.2
2024-08-13 12:23:49 [Debug] - Executing HandleBitwardenSearch
2024-08-13 12:23:49 [Debug] - Auto-lock timer reset
2024-08-13 12:23:49 [Debug] - HandleBitwardenSearch called with query: /unlock [REDACTED]
2024-08-13 12:23:50 [Info] - Bitwarden CLI found. Version: 2024.7.2
2024-08-13 12:23:50 [Debug] - Executing HandleBitwardenSearch
2024-08-13 12:23:50 [Debug] - Auto-lock timer reset
2024-08-13 12:23:50 [Debug] - HandleBitwardenSearch called with query: /unlock [REDACTED]
2024-08-13 12:23:50 [Debug] - [REDACTED SENSITIVE INFORMATION]
2024-08-13 12:23:50 [Debug] - [REDACTED SENSITIVE INFORMATION]
2024-08-13 12:23:50 [Info] - Bitwarden CLI found. Version: 2024.7.2
2024-08-13 12:23:50 [Debug] - Executing HandleBitwardenSearch
2024-08-13 12:23:50 [Debug] - Auto-lock timer reset
2024-08-13 12:23:50 [Debug] - HandleBitwardenSearch called with query: /unlock [REDACTED]
2024-08-13 12:23:50 [Debug] - [REDACTED SENSITIVE INFORMATION]
2024-08-13 12:23:50 [Info] - Bitwarden CLI found. Version: 2024.7.2
2024-08-13 12:23:50 [Debug] - Executing HandleBitwardenSearch
2024-08-13 12:23:50 [Debug] - Auto-lock timer reset
2024-08-13 12:23:50 [Debug] - HandleBitwardenSearch called with query: /unlock [REDACTED]
2024-08-13 12:23:50 [Info] - Bitwarden CLI found. Version: 2024.7.2
2024-08-13 12:23:50 [Debug] - Executing HandleBitwardenSearch
2024-08-13 12:23:50 [Debug] - Auto-lock timer reset
2024-08-13 12:23:50 [Debug] - HandleBitwardenSearch called with query: /unlock [REDACTED]
2024-08-13 12:23:50 [Debug] - [REDACTED SENSITIVE INFORMATION]
2024-08-13 12:23:50 [Info] - Bitwarden CLI found. Version: 2024.7.2
2024-08-13 12:23:50 [Debug] - Executing HandleBitwardenSearch
2024-08-13 12:23:50 [Debug] - Auto-lock timer reset
2024-08-13 12:23:50 [Debug] - HandleBitwardenSearch called with query: /unlock [REDACTED]
2024-08-13 12:23:51 [Info] - Bitwarden CLI found. Version: 2024.7.2
2024-08-13 12:23:51 [Debug] - Executing HandleBitwardenSearch
2024-08-13 12:23:51 [Debug] - Auto-lock timer reset
2024-08-13 12:23:51 [Debug] - HandleBitwardenSearch called with query: /unlock [REDACTED]
2024-08-13 12:23:52 [Debug] - Starting UnlockVault method
2024-08-13 12:23:52 [Debug] - Starting Bitwarden CLI unlock process with None quoting
2024-08-13 12:23:54 [Debug] - Unlock process completed for None quoting
2024-08-13 12:23:54 [Error] - [REDACTED SENSITIVE INFORMATION]
2024-08-13 12:23:54 [Debug] - Starting Bitwarden CLI unlock process with Single quoting
2024-08-13 12:23:55 [Debug] - Unlock process completed for Single quoting
2024-08-13 12:23:55 [Error] - [REDACTED SENSITIVE INFORMATION]
2024-08-13 12:23:55 [Debug] - Starting Bitwarden CLI unlock process with Double quoting
2024-08-13 12:23:57 [Debug] - Unlock process completed for Double quoting
2024-08-13 12:23:57 [Error] - [REDACTED SENSITIVE INFORMATION]
2024-08-13 12:23:57 [Error] - Failed to unlock the vault with all quoting methods


[BitwardenFlow_20240813.log](https://github.com/user-attachments/files/16603991/BitwardenFlow_20240813.log)

**Comment by abbasou** [comment] 2024-08-13 18:52
Update: Really weird: Did an actual cmd shell  `bw lock` and then `bw unlock`, restarted FL, and it finally logged in correctly. Sorry, don't know what else to tell you.

[BitwardenFlow_20240813 trimmed.log](https://github.com/user-attachments/files/16604116/BitwardenFlow_20240813.trimmed.log)

**Comment by RedMageKnight** [comment] 2024-08-13 20:30
At this point, I don't really know what else to say either - I didn't design this with a custom Bitwarden instance in mind, only the online Bitwarden hosted one and I know that works. I had intended on trying to get it to work in a future update by providing all of the server settings available as options to supply but I don't really have a way to test it without my own instance, and while I used to have one, I no longer do and I don't know how long it's going to take me to set up that environment again and continue testing to try and get it working.

I know some people have gotten it to work with theirs, but I can't confirm exactly all they've done one way or another.

I'm sorry I don't have a better answer for you, and I'll keep working on incorporating custom server options natively, but I don't have a timeframe unfortunately.

**Comment by flooxo** [comment] 2024-08-14 10:15
> Update: Really weird: Did an actual cmd shell `bw lock` and then `bw unlock`, restarted FL, and it finally logged in correctly. Sorry, don't know what else to tell you.
> 
> [BitwardenFlow_20240813 trimmed.log](https://github.com/user-attachments/files/16604116/BitwardenFlow_20240813.trimmed.log)

Have you tried resetting your API key in the web vault? Did that change anything?

**Comment by abbasou** [comment] 2024-08-14 17:48
> > Update: Really weird: Did an actual cmd shell `bw lock` and then `bw unlock`, restarted FL, and it finally logged in correctly. Sorry, don't know what else to tell you.
> > [BitwardenFlow_20240813 trimmed.log](https://github.com/user-attachments/files/16604116/BitwardenFlow_20240813.trimmed.log)
> 
> Have you tried resetting your API key in the web vault? Did that change anything?

So I came back today (this is on my work PC) and was unable to unlock. Reset API key, still nothing. Uninstalled plugin and reinstalled from store, still nothing. Tried `bw lock` and `bw unlock` in shell, still nothing. Tried various combinations of `bw lock`, close FL, restart, `bw unlock`, but still nothing.

Eventually did `bw lock`, close FL, `bw unlock`, start FL, and finally got it to unlock. At this point I suspect something in our particular vaultwarden instance. It runs as a container on a Synology NAS, and who knows what kind of config it might have that is messing with things. I don't have access to the containers, nor would I know anything about configuring them, so I just set autolock to never and cross my fingers. Lol

**Comment by RedMageKnight** [comment] 2024-09-04 16:01
Closing for now as I can't replicate this issue and it has morphed into supporting a self-hosted instance which works by setting up the server parameters in the CLI beforehand but was not in the original scope of design. Will eventually add the ability to add the server parameters from the UI in a future update but have been fairly busy as of lately.

**Closed by RedMageKnight** 2024-09-04 16:01 UTC
Labels: bug
